config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/menu', to: "pages#menu", as: "menu"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # config/routes.rb
  resources :campaigns, only: [:create, :new, :edit, :index, :show]
  get '/home', to: 'campaigns#home'

  resources :choose_batches, only: %i[new create]
  resources :choose_recruiters, only: %i[new create]
  resources :choose_times, only: %i[new create]
  #As a candidate I can see all recruiters of the campaign
  get "campaigns/:campaign_id/recruiters", to: "recruiters#index", as: "recruiters"

  #As a candidate or recruiter I can see all my bookings
  get "bookings", to: "bookings#index", as: :list_bookings

  #As a recruiter I can see all students of the campaign
  get "campaigns/:campaign_id/students", to: "students#index", as: "students"
=begin
resources :campaigns do
      resources :users, only: [:index], as: :recruiters
  end
=end
  post "cal_endpoint", to: 'bookings#handle_cal_webhook'

  get 'recruiters/:id', to: 'recruiters#show', as: 'recruiter'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
  <!-- navbar code here -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="height: 83px;">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <% if current_user.role == 'manager' %>
              <%= link_to 'Campaign meetings', list_bookings_path, class: "nav-link" %>
            <% elsif current_user.role == 'student' %>
              <%= link_to "View my bookings", list_bookings_path, class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <div style="background-color: <%= current_user.initials_color %>" class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown">
              <span class="avatar"><%= current_user.initials.upcase %></span>
            </div>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.role == 'manager' %>
                <%= link_to 'Create campaign', new_choose_batch_path, class: "dropdown-item" %>
                <%= link_to 'My campaign stats', "#", class: "dropdown-item" %>
              <% elsif current_user.role == 'student' %>
                <%= link_to 'My bookings', list_bookings_path(current_user), class: "dropdown-item" %>
                <%= link_to 'Recruiters', recruiters_path(current_user.campaigns.last), class: "dropdown-item" %>
              <% elsif current_user.role == 'recruiter' %>
                <%# lol %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>

app/views/shared/cal_widget.html.erb
<!-- Cal element-click embed code begins -->
<script type="text/javascript">
(function (C, A, L) { let p = function (a, ar) { a.q.push(ar); }; let d = C.document; C.Cal = C.Cal || function () { let cal = C.Cal; let ar = arguments; if (!cal.loaded) { cal.ns = {}; cal.q = cal.q || []; d.head.appendChild(d.createElement("script")).src = A; cal.loaded = true; } if (ar[0] === L) { const api = function () { p(api, arguments); }; const namespace = ar[1]; api.q = api.q || []; typeof namespace === "string" ? (cal.ns[namespace] = api) && p(api, ar) : p(cal, ar); return; } p(cal, ar); }; })(window, "https://app.cal.com/embed/embed.js", "init");
Cal("init", {origin:"https://app.cal.com"});

// Important: Make sure to add `data-cal-link="antoine-vaissi--lumxva/15min"` attribute to the element you want to open Cal on click
Cal("ui", {"styles":{"branding":{"brandColor":"#000000"}},"hideEventTypeDetails":false});
</script>
<!-- Cal element-click embed code ends -->