config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/menu', to: "pages#menu", as: "menu"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # config/routes.rb
  resources :campaigns, only: [:create, :new, :edit, :index, :show]
  get '/home', to: 'campaigns#home'

  resources :choose_batches, only: %i[new create]
  resources :choose_recruiters, only: %i[new create]
  resources :choose_times, only: %i[new create]
  #As a candidate I can see all recruiters of the campaign
  get "campaigns/:campaign_id/recruiters", to: "recruiters#index", as: "recruiters"

  #As a candidate or recruiter I can see all my bookings
  get "bookings", to: "bookings#index", as: :list_bookings

  #As a recruiter I can see all students of the campaign
  get "campaigns/:campaign_id/students", to: "students#index", as: "students"
=begin
resources :campaigns do
      resources :users, only: [:index], as: :recruiters
  end
=end
  post "cal_endpoint", to: 'bookings#handle_cal_webhook'

  get 'recruiters/:id', to: 'recruiters#show', as: 'recruiter'

end

app/views/pages/_manager_links.html.erb
<%= link_to new_campaign_path, class: "btn btn-lg btn-primary my-2" do %>
  Create a Campaign
  <i class="fa-solid fa-cube"></i>
<% end %>

<%= link_to new_campaign_path, class: "btn btn-lg btn-outline-light my-2" do %>
  Show bookings
  <i class="fa-solid fa-cube"></i>
<% end %>

app/views/pages/_recruiter_links.html.erb
<%= link_to new_campaign_path, class: "btn btn-primary my-2" do %>
  Show my candidates bookings
  <i class="fa-solid fa-cube"></i>
<% end %>

app/views/pages/_student_links.html.erb
<%= link_to campaign_path(current_user.campaigns.last), class: "btn btn-lg btn-primary my-2" do %>
  Book a new meeting with a recruiter
  <i class="fa-solid fa-cube"></i>
<% end %>

<%= link_to list_bookings_path, class: "btn btn-lg btn-outline-light my-2" do %>
  Show my bookings with recruiters
  <i class="fa-solid fa-cube"></i>
<% end %>

app/views/pages/home.html.erb
<% if user_signed_in? %>

  <div class="d-flex flex-column align-items-center justify-content-center" style="height: calc(100vh - 83px); background-size: cover; background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= image_url("background-image.jpg") %>')">

    <% if current_user.role == "manager" %>
      <div class="d-flex flex-column justify-items-between my-5">
        <%= render "manager_links" %>
      </div>
    <% end %>

    <% if current_user.role == "recruiter" %>
      <div class="d-flex flex-column justify-items-between my-5">
        <%= render "recruiter_links" %>
      </div>
    <% end %>

    <% if current_user.role == "student" %>
      <div class="d-flex flex-column justify-items-between my-5">
        <%= render "student_links" %>
      </div>
    <% end %>

  </div>

<% else %>
  <div class="banner">
    <div class="banner-content text-center">
      <h1>Organising career speed dating meetings is a breeze</h1>
      <p>Hit the button below to get started</p>
        <%= link_to "Start now", menu_path, class: "btn btn-lg btn-primary"  %>
    </div>
  </div>
<% end %>

app/views/pages/menu.html.erb
<% if user_signed_in? %>
  <div class="d-flex flex-column align-items-center justify-content-center" style="height: calc(100vh - 83px); background-size: cover; background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= image_url("background-image.jpg") %>')">
   

    <% if current_user.role == "manager" %>
      <div class="d-flex flex-column justify-items-between my-5">
        <%= render "manager_links" %>
      </div>
    <% end %>

    <% if current_user.role == "recruiter" %>
      <div class="d-flex flex-column justify-items-between my-5">
        <%= render "recruiter_links" %>
      </div>
    <% end %>

    <% if current_user.role == "student" %>
      <div class="d-flex flex-column justify-items-between my-5">
        <%= render "student_links" %>
      </div>
    <% end %>

  </div>

<% end %>