config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/menu', to: "pages#menu", as: "menu"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # config/routes.rb
  resources :campaigns, only: [:create, :new, :edit, :index, :show]
  get '/home', to: 'campaigns#home'

  resources :choose_batches, only: %i[new create]
  resources :choose_recruiters, only: %i[new create]
  resources :choose_times, only: %i[new create]
  #As a candidate I can see all recruiters of the campaign
  get "campaigns/:campaign_id/recruiters", to: "recruiters#index", as: "recruiters"

  #As a candidate or recruiter I can see all my bookings
  get "bookings", to: "bookings#index", as: :list_bookings

  #As a recruiter I can see all students of the campaign
  get "campaigns/:campaign_id/students", to: "students#index", as: "students"
=begin
resources :campaigns do
      resources :users, only: [:index], as: :recruiters
  end
=end
  post "cal_endpoint", to: 'bookings#handle_cal_webhook'

  get 'recruiters/:id', to: 'recruiters#show', as: 'recruiter'

end

app/models/choose_recruiter.rb
class ChooseRecruiter
  include ActiveModel::Model
  attr_accessor :user_ids
  validates :user_ids, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_one_attached :photo
  has_many :users
end

app/controllers/choose_recruiters_controller.rb
class ChooseRecruitersController < ApplicationController

  def new
    @recruiter = ChooseRecruiter.new
    @recruiters = User.where(role: "recruiter")
  end

  def create
    @recruiter = ChooseRecruiter.new(recruiter_params)
    if @recruiter.valid?
      session[:campaign][:user_ids] = @recruiter.user_ids.compact_blank

      redirect_to new_choose_time_path
    else
      @recruiters = User.where(role: "recruiter")
      render :new
    end

  end

  def recruiter_params
    params.require(:choose_recruiter).permit(user_ids: [])
  end
end

app/views/choose_recruiters/new.html.erb
<div class="container">
  <div class="row mt-5">
    <h3 class="text-center">Choose the recruiters you want to include</h3>
  </div>
  <%= simple_form_for @recruiter do |f| %>
    <div class="row mt-5">
      <div class="col-8">
        <%= f.input :user_ids,
                    as: :check_boxes,
                    collection: @recruiters.sort_by { |recruiter| recruiter.company.name },
                    input_html: {
                      class: 'tag-selector'
                    },
                    legend_tag: false,
                    item_wrapper_class: 'recruiter-tag-wrapper',
                    label_method: -> (recruiter) {
                      content_tag(:div, class: 'd-flex justify-content-between') do
                          [recruiter.company.name, recruiter.full_name].reduce('') { |c, x|
                            c << content_tag(:span, x)
                          }.html_safe
                      end
                    } %>
      </div>
      <div class="col-4">
        <%= image_tag "recruiters.jpg", class: 'w-100 form-side-image' %>
      </div>
    </div>
    <div class="row mt-5 mb-5">
      <%= f.button :submit, class: "btn btn-primary d-block mx-auto w-50", value: "Next, choose times" %>
    </div>
  <% end %>
</div>

app/views/choose_recruiters/~~~new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-8">
      <%= simple_form_for @recruiter do |f| %>
        <div class="row">
          <% @recruiters.each do |recruiter| %>
            <div class="col-md-4 mb-3">
              <div class="card-product d-flex">
                <div class="card-product-img">
                  <%= link_to recruiter_path(recruiter) do %>
                    <% if recruiter.company.photo.attached? %>
                      <%= cl_image_tag recruiter.company.photo.key %>
                    <% else %>
                      <%= image_tag "no_photo.png" %>
                    <% end %>
                  <% end %>
                </div>
                <div class="card-product-infos flex-grow-1">
                  <div class="h2"><%= recruiter.full_name_and_company %></div>
                  <p>"<strong><%= recruiter.tagline %></strong>"</p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <%= f.button :submit, class: "btn btn-primary d-block mx-auto w-50", value: "Next, choose times" %>
      <% end %>
    </div>
    <div class="col-4">
      <%= image_tag "recruiters.jpg", class: 'w-100 form-side-image' %>
    </div>
  </div>
</div>